uk_dict = {
	'q01':{
	'A': 'Never heard of them',
	'B': 'Heard but not sure what they are',
	'C': 'Know what they are',
	'D': 'Know a lot about them',
	'E': 'I am an expert'
	},
	'q02':{
	'A': 'There are usually AI applications on Android and iOS smart phones',
	'B': 'AI remains exclusively in academic research and cannot be commercialised yet',
	'C': 'AI is a collection of connected machines',
	'D': 'AI is only capable of performing a narrow range of tasks today',
	'E': 'AI is capable of driving cars without human supervision',
	'F': 'AI can call and speak to a restaurant on the phone to make reservations',
	'G': 'AI can voluntarily modify itself and evolve',
	'H': 'AI can write human grade articles with a clear theme with correct grammar and advanced vocabulary',
	'I': 'The Recurrent Neural Network architecture is likely to continue losing popularity',
	'J': 'The Transformer architecture is designed for self-driving cars'
	},
	'q03':{
	'A': 'Yes',
	'B': 'No',
	'C': 'Not sure'
	},
	'q10':{
	'A': 'Increased efficiency and productivity',
	'B': 'Outsourcing of repetitive and boring work to machines',
	'C': 'Better professional performance',
	'D': 'New business opportunities created',
	'E': 'none'
	},
	'q11':{
	'A': 'Artificial Intelligence not 100% reliable and can lead me to make mistakes',
	'B': 'reduced job security',
	'C': 'reduced human interaction',
	'D': 'Lack of/misaligned accountability when AI misfires',
	'E': 'none'
	},
	'q14':{
	'A': 'more free time for family, friends and self',
	'B': 'more flexibility in life',
	'C': 'increased convenience and more reliable services',
	'D': 'increased physical wellbeing being thanks to AI powered healthcare',
	'E': 'none'
	},
	'q15':{
	'A': 'potential surveillance, privacy and data security related issues',
	'B': 'reduced social interaction',
	'C': 'more fake information generated by AI',
	'D': 'financial barrier of AI leading to reduced social mobility',
	'E': 'none'
	},
	'q16':{
	'A': 'Artificial Intelligence technologies will create less jobs than it eliminates',
	'B': 'Artificial Intelligence technologies will create more jobs than it eliminates',
	'C': 'Artificial intelligence will have no impact on employment'
	},
	'q17':{
	'A': 'Yes',
	'B': 'No',
	'C': 'Maybe'
	},
	'q18':{
	'A': 'Teachers',
	'B': 'Telephone operators',
	'C': 'Accountants and auditors',
	'D': 'Restaurant chefs',
	'E': 'Photographers',
	'F': 'Data scientist',
	'G': 'Lawyer',
	'H': 'Construction and Related Workers',
	'I': 'Medical Doctors',
	'J': 'Flight Attendants'
	},
	'q19':{
	'A': 'Lack of human interaction',
	'B': 'Highly repetitive',
	'C': 'Lack of prestige',
	'D': 'Skills required for the job is expensive and hard to come by',
	'E': 'Lack of creativity'
	},
	'q20':{
	'A': 'Yes',
	'B': 'No',
	'C': 'Maybe'
	},
	'q21':{
	'A': 'AI can make mistakes when making important decisions',
	'B': 'Privacy and data security concerns',
	'C': 'AI can be biased and reinforce existing social injustice',
	'D': 'AI\'s inability to understand nuance in human communication',
	'E': 'AI can turn on mankind'
	},
	'q22':{
	'A': 'It will not happen',
	'B': 'Isolated cases with insignicant impact',
	'C': 'Isolated cases with significant impact',
	'D': 'Widespread phenomenon with managable impact',
	'E': 'Widespread phenomenon with signnificant impact'
	},
	'q23':{
	'A': 'Yes',
	'B': 'No',
	'C': 'Not sure'
	},
	'q24':{
	'A': 'Ensuring objectivity in AI decision making',
	'B': 'Data security and personal privacy',
	'C': 'Keeping the technology off limit to highly sensitive applications (i.e. AI powered public surveillance)',
	'D': 'Establishing accountability for AI\'s potential adverse impact'
	},
	'q25':{
	'A': '15 or younger',
	'B': 'between 16 and 25',
	'C': 'between 26 and 35',
	'D': 'between 36 and 45',
	'E': 'between 46 and 55',
	'F': '56 or older'
	},
	'q27':{
	'A': 'High school diploma or equivalent',
	'B': 'Bachelor\'s degree or equivalent',
	'C': 'Master\'s degree or equivalent',
	'D': 'Doctorate, its equivalent or higher',
	'E': 'Technical diploma or equivalent'
	},
	'q28':{
	'A': 'Yes',
	'B': 'No'
	}
}



fr_dict = {
	'q01':{
	'A': 'Je n\'en ai jamais entendu parler',
	'B': 'J\'en ai entendu parler mais je ne suis pas sur de ce que c\'est',
	'C': 'Je sais ce que c\'est',
	'D': 'J\'en sais beaucoup sur le sujet',
	'E': 'Je suis expert'
	},
	'q02':{
	'A': 'Il y a généralement des applications d\'intelligence artificielle sur les smart phones Android et iOS',
	'B': 'L\'IA reste exclusivement dans la recherche académique et ne peut pas encore être commercialisée',
	'C': 'L\'IA est un ensemble de machines connectées',
	'D': 'L\'IA n\'est capable d\'effectuer qu\'une gamme limitée de tâches aujourd\'hui',
	'E': 'L\'IA est capable de conduire des voitures sans surveillance humaine',
	'F': 'L\'IA peut appeler et parler à un restaurant au téléphone pour faire des réservations',
	'G': 'L\'IA peut se modifier et évoluer volontairement',
	'H': 'L’IA peut rédiger des articles de qualité humaine avec un thème clair, une grammaire correcte et un vocabulaire avancé',
	'I': 'L’architecture du réseau neuronal récurrent risque de continuer à perdre de sa popularité',
	'J': 'L\'architecture Transformer est conçue pour les voitures autonomes'
	},
	'q03':{
	'A': 'Oui',
	'B': 'Non',
	'C': 'Peut-être'
	},
	'q10':{
	'A': 'Augmentation de l\'efficacité et de la productivité',
	'B': 'Externalisation du travail répétitif et ennuyeux aux machines',
	'C': 'Meilleure performance professionnelle',
	'D': 'Nouvelles opportunités commerciales',
	'E': 'aucun'
	},
	'q11':{
	'A': 'L\'intelligence artificielle n\'est pas fiable à 100% et peut me conduire à commettre des erreurs',
	'B': 'Sécurité d\'emploi réduite',
	'C': 'Interaction humaine réduite',
	'D': 'Absence de responsabilité / désalignement en cas d\'erreurs commises par l\'IA',
	'E': 'aucun'
	},
	'q14':{
	'A': 'plus de temps libre pour la famille, les amis et soi-même',
	'B': 'plus de flexibilité dans la vie',
	'C': 'commodité accrue et services plus fiables',
	'D': 'bien-être physique grâce aux soins de santé fonctionnant à l\'IA',
	'E': 'aucun'
	},
	'q15':{
	'A': 'problèmes potentiels de surveillance, de confidentialité et de sécurité des données',
	'B': 'interaction sociale réduite',
	'C': 'plus d\'informations factices générées par l\'IA',
	'D': 'barrière financière de l\'IA entraînant une mobilité sociale réduite',
	'E': 'aucun'
	},
	'q16':{
	'A': 'Les technologies de l\'intelligence artificielle créeront moins d\'emplois qu\'elles n\'en supprimeront',
	'B': 'Les technologies de l\'intelligence artificielle créeront plus d\'emplois qu\'elle n\'en supprimeront',
	'C': 'L\'intelligence artificielle n\'aura aucun impact sur l\'emploi'
	},
	'q17':{
	'A': 'Oui',
	'B': 'Non',
	'C': 'Peut-être'
	},
	'q18':{
	'A': 'Enseignants',
	'B': 'Opérateurs téléphoniques',
	'C': 'Comptables et auditeurs',
	'D': 'Chefs de restaurant',
	'E': 'Photographes',
	'F': 'Data scientists',
	'G': 'Avocats',
	'H': 'Travailleurs de la construction',
	'I': 'Médecins',
	'J': 'Agent de bord (avion)'
	},
	'q19':{
	'A': 'Manque d\'interaction humaine',
	'B': 'Très répétitif',
	'C': 'Manque de prestige',
	'D': 'Les compétences requises pour le travail sont coûteuses et difficiles à trouver',
	'E': 'Manque de créativité'
	},
	'q20':{
	'A': 'Oui',
	'B': 'Non',
	'C': 'Peut-être'
	},
	'q21':{
	'A': 'L\'IA peut commettre des erreurs en prenant des décisions importantes',
	'B': 'Problèmes de confidentialité et de sécurité des données',
	'C': 'L\'IA peut être biaisée et renforcer l\'injustice sociale existante',
	'D': 'L\'incapacité de l\'IA à comprendre les nuances de la communication humaine',
	'E': 'L\'IA peut menacer l\'humanité'
	},
	'q22':{
	'A': 'Ça n\'arrivera pas',
	'B': 'Cas isolés ayant un impact négligeable',
	'C': 'Cas isolés ayant un impact significatif',
	'D': 'Phénomène répandu à impact maîtrisable',
	'E': 'Phénomène répandu à impact significatif'
	},
	'q23':{
	'A': 'Oui',
	'B': 'Non',
	'C': 'Peut-être'
	},
	'q24':{
	'A': 'Assurer l\'objectivité dans la prise de décision en IA',
	'B': 'Sécurité des données et vie privée',
	'C': 'Limiter la technologie aux applications hautement sensibles (par exemple: surveillance publique alimentée par l’IA)',
	'D': 'Établir la responsabilité pour l\'impact négatif potentiel d\'IA'
	},
	'q25':{
	'A': '15 ans ou moins',
	'B': 'entre 16 et 25',
	'C': 'entre 26 et 35',
	'D': 'entre 36 et 45',
	'E': 'entre 46 et 55',
	'F': '56 ans et plus'
	},
	'q27':{
	'A': 'Diplôme d\'études secondaires ou l\'équivalent',
	'B': 'Bachelor/BTS ou équivalent',
	'C': 'Master ou équivalent',
	'D': 'Doctorat, son équivalent ou supérieur',
	'E': 'Diplôme technique ou équivalent'
	},
	'q28':{
	'A': 'Oui',
	'B': 'Non'
	}
}


de_dict = {
	'q01':{
	'A': 'Nie davon gehört',
	'B': 'Gehört, aber nicht sicher, was sie ist',
	'C': 'Weiß, was sie ist',
	'D': 'Ich weiß viel über sie',
	'E': 'Ich bin ein Experte'
	},
	'q02':{
	'A': 'Es gibt normalerweise KI-Applikationen auf Android- und iOS-Smartphones',
	'B': 'KI bleibt ausschließlich in der akademischen Forschung und kann noch nicht kommerziell genutzt werden',
	'C': 'KI ist eine Sammlung verbundener Maschinen',
	'D': 'KI ist heute nur in der Lage, ein begränztes Aufgabenspektrum zu bewältigen',
	'E': 'KI ist in der Lage, Autos ohne menschliche Aufsicht zu fahren',
	'F': 'KI kann ein Restaurant anrufen, um Reservierungen vorzunehmen',
	'G': 'KI kann sich freiwillig verändern und weiterentwickeln',
	'H': 'KI kann menschenähnlich Artikel mit einem klaren Thema mit korrekter Grammatik und fortgeschrittenem Vokabular schreiben',
	'I': 'Die Architektur eines Recurrent Neural Network wird wahrscheinlich weiterhin an Popularität verlieren',
	'J': 'Die Transformer-Architektur ist für selbstfahrende Autos konzipiert'
	},
	'q03':{
	'A': 'Ja',
	'B': 'Nein',
	'C': 'Vielleicht'
	},
	'q10':{
	'A': 'Erhöhte Effizienz und Produktivität',
	'B': 'Auslagerung von sich wiederholenden und langweiligen Arbeiten an Maschinen',
	'C': 'Bessere berufliche Leistung',
	'D': 'Neue Geschäftsmöglichkeiten geschaffen',
	'E': 'keine'
	},
	'q11':{
	'A': 'Künstliche Intelligenz ist nicht 100% zuverlässig und kann mich zu Fehlern führen',
	'B': 'geringere Arbeitsplatzsicherheit',
	'C': 'reduzierte menschliche Interaktion',
	'D': 'Fehlende / falsch ausgerichtete Verantwortlichkeit bei KI-Aussetzern',
	'E': 'keine'
	},
	'q14':{
	'A': 'Mehr Freizeit für Familie, Freunde und sich selbst',
	'B': 'mehr Flexibilität im Leben',
	'C': 'Mehr Komfort und zuverlässigere Dienste',
	'D': 'Verbessertes körperliches Wohlbefinden dank KI-gestützter Gesundheitsversorgung',
	'E': 'keine'
	},
	'q15':{
	'A': 'potenzielle Probleme im Zusammenhang mit Überwachung, Datenschutz und Datensicherheit',
	'B': 'reduzierte soziale Interaktion',
	'C': 'mehr gefälschte Informationen von AI generiert',
	'D': 'Die finanzielle Barriere von AI führt zu einer Einschränkung der sozialen Mobilität',
	'E': 'keine'
	},
	'q16':{
	'A': 'Künstliche Intelligenz-Technologien schaffen weniger Arbeitsplätze als sie beseitigen',
	'B': 'Künstliche Intelligenz-Technologien werden mehr Arbeitsplätze schaffen, als sie beseitigen',
	'C': 'Künstliche Intelligenz wird keine Auswirkungen auf die Beschäftigung haben'
	},
	'q17':{
	'A': 'Ja',
	'B': 'Nein',
	'C': 'Vielleichte'
	},
	'q18':{
	'A': 'Lehrer',
	'B': 'Telefonoperator',
	'C': 'Buchhalter und Wirtschaftsprüfer',
	'D': 'Restaurantköche',
	'E': 'Fotografen',
	'F': 'Datenwissenschaftler',
	'G': 'Anwälte',
	'H': 'Bau- und verwandte Berufe',
	'I': 'Ärzte',
	'J': 'Flugbegleiter'
	},
	'q19':{
	'A': 'Mangel an menschlicher Interaktion',
	'B': 'Sehr repetitiv',
	'C': 'Mangel an Prestige',
	'D': 'Die für den Job erforderlichen Fähigkeiten sind teuer und schwer zu bekommen',
	'E': 'Mangel an Kreativität'
	},
	'q20':{
	'A': 'Ja',
	'B': 'Nein',
	'C': 'Vielleicht'
	},
	'q21':{
	'A': 'KI kann bei wichtigen Entscheidungen Fehler machen',
	'B': 'Bedenken hinsichtlich Datenschutz und Datensicherheit',
	'C': 'KI kann voreingenommen sein und bestehende soziale Ungerechtigkeiten verstärken',
	'D': 'AI ist nicht in der Lage, Nuancen in der menschlichen Kommunikation zu verstehen',
	'E': 'KI kann sich gegen die Menschheit wenden'
	},
	'q22':{
	'A': 'Es wird nicht passieren',
	'B': 'Einzelfälle mit geringfügigen Auswirkungen',
	'C': 'Einzelfälle mit erheblichen Auswirkungen',
	'D': 'Weit verbreitetes Phänomen mit überschaubaren Auswirkungen',
	'E': 'Weit verbreitetes Phänomen mit erheblichen Auswirkungen'
	},
	'q23':{
	'A': 'Ja',
	'B': 'Nein',
	'C': 'Vielleicht'
	},
	'q24':{
	'A': 'Objektivität in der Entscheidungsfindung der KI sicherstellen',
	'B': 'Datensicherheit und Datenschutz',
	'C': 'Beschränkung der Abschaltung der Technologie auf hochsensible Anwendungen (d. H. Öffentliche Überwachung durch KI)',
	'D': 'Rechenschaftspflicht für die potenziellen nachteiligen Auswirkungen von AI'
	},
	'q25':{
	'A': '15 oder jünger',
	'B': 'zwischen 16 und 25',
	'C': 'zwischen 26 und 35',
	'D': 'zwischen 36 und 45',
	'E': 'zwischen 46 und 55',
	'F': '56 oder älter'
	},
	'q27':{
	'A': 'Abitur oder gleichwertig',
	'B': 'Bachelor-Abschluss oder gleichwertig',
	'C': 'Master-Abschluss oder gleichwertig',
	'D': 'Doktorat, Äquivalent oder höher',
	'E': 'Technisches Diplom oder gleichwertig'
	},
	'q28':{
	'A': 'Ja',
	'B': 'Nein'
	}
}

answer_dicts = {'en': uk_dict, 'fr': fr_dict, 'de': de_dict}