country_conversion_dict = {'Australia':'non_WE',
 'BE':'BE',
 'Belgique':'BE',
 'Belgium':'BE',
 'CH':'CH',
 'Canada':'non_WE',
 'DE':'DE',
 'Deutschland ':'DE',
 'ENGLAND':'UK',
 'England':'UK',
 'FR':'FR',
 'FRANCE':'FR',
 'Finland ':'non_WE',
 'France':'FR',
 'France ':'FR',
 'Germany':'DE',
 'Hong Kong':'non_WE',
 'Ireland':'IE',
 'Luxembourg':'LU',
 'NETHERLANDS':'NL',
 'Netherlands':'NL',
 'POrtugal':'PT',
 'Paris ':'FR',
 'Poland':'non_WE',
 'Schweiz':'CH',
 'Scotland':'UK',
 'Spain':'ES',
 'Switzerland':'CH',
 'Taiwan':'non_WE',
 'The Netherlands':'NL',
 'UK':'UK',
 'UNITED KINGDOM':'UK',
 'USA':'non_WE',
 'United Kingdom':'UK',
 'United kingdom':'UK',
 'fr':'FR',
 'france':'FR',
 'london':'UK',
 'nl':'NL',
 'uk':'UK',
 'united kingdom':'UK'}

