jobs_dict = {'student, business administration, working student software company':'student_various',
 'microbiologist in agribusiness':'engineering_various',
 'it student':'student_various',
 'data scientist':'comp_sci_software_eng',
 'government':'public_service',
 'student at hec':'student_various',
 'student':'student_various',
 'maths student':'student_various',
 'software professional':'comp_sci_software_eng',
 'retail':'other',
 'prison officer':'public_service',
 'student (philosophy)':'student_various',
 'english and creative writing student':'student_various',
 'educator':'education',
 'process and biotechnology engineer':'engineering_various',
 'it engineer':'comp_sci_software_eng',
 'hydraulic studies manager':'mgmt_various',
 'it%20consultant':'professional_services',
 'commercial employee':'other',
 'housewife':'other',
 'data science for good/pizza':'comp_sci_software_eng',
 'm&a analyst':'finance_acc_aud',
 'it support technician':'other',
 'agronomist':'research',
 'general engineering':'engineering_various',
 'it intern':'comp_sci_software_eng',
 'lecturer in economics':'research',
 'medical':'medical_professionals',
 'data processing':'other',
 'information technology':'comp_sci_software_eng',
 'consultancy':'professional_services',
 'advertising student':'student_various',
 'commerce':'mgmt_various',
 'technical framework':'other',
 'physics':'research',
 'former medical admin/biomedical scientist':'medical_professionals',
 'self employed':'other',
 'psychology lecturer':'research',
 'hotel and catering':'other',
 'computer engineer':'comp_sci_software_eng',
 'mathematician':'research',
 'special educational needs teacher':'education',
 'maintenance mechanics and electrics':'other',
 'motorist':'other',
 'plant operator':'other',
 'financial analyst':'finance_acc_aud',
 'scaffolders':'other',
 'medical student':'medical_professionals',
 'student in data science':'comp_sci_software_eng',
 'restaurant service':'other',
 'lawyer':'other',
 'administrative assistant':'mgmt_various',
 'supervisor':'mgmt_various',
 'commercial computer':'comp_sci_software_eng',
 'economist':'research',
 'health insurance advisor':'other',
 'assistant to the management':'mgmt_various',
 'hr':'mgmt_various',
 'ib student':'student_various',
 'communal secretary':'other',
 'care assistant':'other',
 'cnc milling':'other',
 'service agent, service agent':'other',
 'software developer':'comp_sci_software_eng',
 'pension':'unemployed_retired',
 'employee':'other',
 'management student':'student_various',
 'automotive designer':'other',
 'student entrepreneur':'student_various',
 'consultant digital':'internet_digital_non_engineering',
 'programmer':'comp_sci_software_eng',
 'real estate':'other',
 'self employed mechanic':'other',
 'administrative manager':'mgmt_various',
 'banking':'finance_acc_aud',
 'machine operator':'other',
 'cleaning man':'other',
 'financial services consultant':'finance_acc_aud',
 'economics student':'student_various',
 'carpenter':'other',
 'technical product designer':'other',
 'baker':'other',
 'receptionist':'other',
 'musician':'media_culture_creative',
 'it support':'other',
 'electrician':'other',
 'finance':'finance_acc_aud',
 'anthropology':'research',
 'phd student':'research',
 'company manager':'mgmt_various',
 'help to the person':'other',
 'data entry freelancer':'other',
 'lecturer':'education',
 'water management':'other',
 'automated line driver':'other',
 'scientist':'research',
 'data analyst':'other',
 'product manager':'mgmt_various',
 'writer':'media_culture_creative',
 'sales representative':'other',
 'consultant in digital transformation':'internet_digital_non_engineering',
 'saas':'internet_digital_non_engineering',
 'dipl.physiker + computer scientist':'comp_sci_software_eng',
 'junior consultant':'professional_services',
 'pensioner':'other',
 'saleswoman':'other',
 'invalid':'unemployed_retired',
 'ingeenier':'engineering_various',
 'electrical mechanic':'other',
 'aviation student':'student_various',
 'climate sciences':'research',
 'it and digital director':'internet_digital_non_engineering',
 'bank':'finance_acc_aud',
 'digital media student':'student_various',
 'project manager / training':'mgmt_various',
 'hr employee':'mgmt_various',
 'statistics':'research',
 'financial audit':'finance_acc_aud',
 'food science student. i will later advise people and a personal conversation and empathy will never replace ki.':'student_various',
 'education assistant':'education',
 'nursery':'medical_professionals',
 'students':'student_various',
 'student with intentions to enter medicine':'student_various',
 "young children's educator":'education',
 'marketing':'other',
 'cnc specialist':'other',
 'phd neuroscience':'research',
 'office assistant':'mgmt_various',
 'physics student':'student_various',
 'student data science':'comp_sci_software_eng',
 'student in business school':'student_various',
 'project director':'mgmt_various',
 'car mechanic':'other',
 'commercial':'other',
 'graphic designer':'media_culture_creative',
 'secretary':'mgmt_various',
 'ict':'comp_sci_software_eng',
 'unemployed':'unemployed_retired',
 'worker':'other',
 'electrical engineering/computer science':'comp_sci_software_eng',
 'student in sustainability & social innovation':'student_various',
 'retailer':'other',
 'events management':'mgmt_various',
 'computer scientist':'comp_sci_software_eng',
 'doctor':'medical_professionals',
 'business employee':'other',
 'master of business administration':'student_various',
 'accounting':'finance_acc_aud',
 'aeronautical engineer':'engineering_various',
 'civil engineer':'engineering_various',
 'higher education administration':'education',
 'business city':'other',
 'sales support':'other',
 'medical researcher':'research',
 'software development':'comp_sci_software_eng',
 'computer science student':'comp_sci_software_eng',
 'construction supervisor telecommunications':'mgmt_various',
 'driver':'other',
 'technician':'other',
 'mechanical engineer packaging':'other',
 'student in horticulture':'student_various',
 'business':'mgmt_various',
 'processing loose':'other',
 'manager':'mgmt_various',
 'i am an educator':'education',
 'engineering student':'student_various',
 'it manager':'mgmt_various',
 'economics':'research',
 'recruitment agency':'other',
 'teacher':'education',
 'promotional media':'media_culture_creative',
 'consultant':'professional_services',
 'education':'education',
 'administrative employee':'mgmt_various',
 'accountant':'finance_acc_aud',
 'logistics agent':'other',
 'barista':'other',
 'seller':'other',
 'engineer for supply engineering': 'engineering_various',
 'soldier and app developer':'comp_sci_software_eng',
 'industrial engineer student':'student_various',
 'psychologist':'research',
 'mechanical engineer':'engineering_various',
 'tax specialist':'finance_acc_aud',
 'student in journalism':'student_various',
 'engineer':'engineering_various',
 'data engineer':'comp_sci_software_eng',
 'delivery man do products.':'other',
 'data science student':'comp_sci_software_eng',
 'director of information systems':'mgmt_various',
 'media':'media_culture_creative',
 'business school':'student_various',
 'tourism':'other',
 'business administrator':'mgmt_various',
 'technical teacher':'education',
 'communication':'media_culture_creative',
 'business school student':'student_various',
 'communication student':'student_various',
 'business/economy student':'student_various',
 'service to individuals':'other',
 'natural sciences':'research',
 'lehramtstudent':'student_various',
 'account manager':'other',
 'student in economic intelligence':'student_various',
 'expert trainer supporting trades':'other'}