
q_options = {
	'How would you rate your personal knowledge of artificial intelligence technologies?':'q01',
	'Which of the following statements are *false* regarding the nature or capabilities of artificial intelligence?':'q02',
	'From a scale of 1 - 7, how would you rate the impact of artificial intelligence technologies on SOCIETY?':'q04_q05',
	'From a scale of 1 - 7, how would you rate the MAGNITUDE of AI\'s impact?':'q06_q07',
	'From a scale of 1 to 7, how would you rate the impact of artificial intelligence on employment and workplace for you?':'q08_q09',
	'Which of the following area(s) do you think your professional life will benefit the most from Artificial Intelligence technologies?':'q10',
	'Which of the following area(s) do you think your professional life will suffer the most from Artificial Intelligence technologies?':'q11',
	'From a scale of 1 to 7, how would you rate the impact of artificial intelligence on your personal life?':'q12_q13',
	'Which of following areas do you think your personal life will benefit the most from Artificial Intelligence technologies?':'q14',
	'Which of following areas do you think your personal life will suffer the most from Artificial Intelligence technologies?':'q15',
	'Which of the following statement do you agree with the most?':'q16',
	'Do you believe you are at risk of being replaced by Artificial Intelligence?':'q17',
	'Please select 3 jobs from the list below that you think are at risk of being replaced by Artificial Intelligence applications in the next 10 years':'q18',
	'Which of the following reasons do you think put a job at risk of being replaced by Artificial Intelligence? If other, please specify':'q19',
	'Do you trust artificial intelligence applications?':'q20',
	'which of the following factor(s) correspond the best to your reasons of distrust of AI?':'q20',
	'To what extent do you believe the misuse of artificial intelligence technologies will occur and impact our societies in the next 10 years?':'q21',
	'Do you think the current regulations are sufficient for protecting public interest?':'q22',
	'If not, which area(s) should be our priorities when it comes to regulation?':'q23',
	'[Demographic] Age?':'q24',
	'[Demographic] Country of Residence':'q25',
	'[Demographic] Profession':'q26',
	'[Demographic] Highest education qualification':'q27',
	'How will life be in 10 years?':'q29',
}